version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - redis-network

volumes:
  redisdata:

networks:
  redis-network:
